title: Wiki.chairat.me
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github: 
  is_project_page: true
  repository_url: https://github.com/pacroy/pacroy.github.io
  repository_name: Wiki.chairat.me
  owner_url: https://github.com/pacroy/
  owner_name: Chairat (Par)