title: pacroy.github.io
description: Visit my latest wiki at wiki.pacroy.com
show_downloads: false
google_analytics: UA-89685926-4
theme: jekyll-theme-cayman
blog_url: https://pacroy.com
github: 
  is_project_page: true
  repository_url: https://github.com/pacroy/pacroy.github.io
  repository_name: wiki.pacroy.com
  owner_url: https://github.com/pacroy/
  owner_name: Chairat (Par)
